CREATE TABLE blogs (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    thumbnail_image_id INT UNSIGNED,
    FOREIGN KEY (thumbnail_image_id) REFERENCES images(id) ON DELETE CASCADE,
    title VARCHAR (255) NOT NULL,
    content TEXT NOT NULL,
    flare_point INT NOT NULL,
    core_point INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL
);